##########################################################
# application.yaml   (used for development purposes)
##########################################################
name: app1
server.servlet.context-path: /app1
server.port: 8080

spring.profiles.active: dev
development-mode: false

###########################################################
# Database Settings
##########################################################
app.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/app1_db
  username: ENC(qxYroU9H2D0/XCgWuAAjB6HI8fRn47Mf)
  password: ENC(o6E0gqe2UrMHFqgX6mh9Fw==)
  maxPoolSize: 10

###########################################################
# Password Encodingse
##########################################################
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: 'ab5823423464j1k2#!!6298-+'


###########################################################
# ElasticSearch Settings
##########################################################
es.url: http://localhost:9200

###########################################################
# Some BS I was screwing with and now I can't delete it
# because apparently I injected it somewhere and the app
# won't compile without it. It's useless.
##########################################################
bypass.id: 5

---
#######################################
# D E V           P R O F I L E
#######################################
spring.profiles: dev

server.port: 8080
development.mode: true
security.mode: whatever

---
#######################################
# P R O D        P R O F I L E
#######################################
spring.profiles: prod

development.mode: false
security.mode: pki

server:
  port: 8443
  ssl:
    key-store: webapp/src/main/dev_resources/myKeystore.jks
    key-store-password: changeit
    key-store-type: JKS
    client-auth: need
    trust-store: webapp/src/main/dev_resources/myTruststore.jks
    trust-store-password: changeit
    trust-store-type: JKS

# Secure the cookies
server.servlet.session.cookie.secure: true
server.servlet.session.cookie.http-only: true
